#!/bin/sh

export dir=$(pwd)

echo "This is the starting directory" $dir

pull()
{

	echo "This is the first parameter value" $1

	cd $dir

	echo "This is the parent directory" $(pwd)

	cd $1

	echo "This is the current directory" $(pwd)

	git pull origin master

}

pull "../app"

pull "../app-ca2"

pull "../app-cidadedecuritiba"

pull "../app-core"

pull "../app-veriwell"

pull "../design"

pull "../game"

pull "../nodeapp"

pull "../third"
