#pragma once


#undef HAVE_STDINT_H
#define HAVE_STDINT_H 1

#undef HAVE_UINT64_T
#define HAVE_UINT64_T 1

#undef HAVE_XRENDERCREATELINEARGRADIENT
#define HAVE_XRENDERCREATELINEARGRADIENT 1

#undef HAVE_XRENDERCREATERADIALGRADIENT
#define HAVE_XRENDERCREATERADIALGRADIENT 1

#undef HAVE_XRENDERCREATECONICALGRADIENT
#define HAVE_XRENDERCREATECONICALGRADIENT 1



