#!/bin/sh

function install()
{
	
        cd ../../../../../../stage/x86

        ./app : app=app-core/netnode_dynamic_web_server_cfg type=application locale=_std schema=_std install build_number=basis

}


install
